In [12]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.


def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError:
    print('Zero cannot divide a number but you are free to try')
except:
    print('I cannot wait to see you prove me wrong')
finally:
    print('Are you satisfied now that you have tried')

Zero cannot divide a number but you are free to try
Are you satisfied now that you have tried


In [3]:
"""  Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]  """


subject = ['Americans', 'Indians']
verb = ['Play', 'watch']
obj = ['Baseball','cricket']

sentence_list = [(sub+' '+ vb + ' ' + ob) for sub in subject for vb in verb for ob in obj]
for sentence in sentence_list:
    print (sentence)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


In [26]:
"""  Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.  """


import numpy as np

def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matx

inputvector = np.array([1,3,5,7,9])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print('The input array is:',inputvector,)
print('Number of columns in output matrix should be:',no_col_opmat,)
print('Vander matrix of the input array in decreasing order of powers:\n\n',op_matx_dec_order,'\n')
print('Vander matrix of the input array in increasing order of powers:\n\n',op_matx_inc_order,'\n')

inputvector = np.array([2,4,6,8,10])
no_col_opmat = 5
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

print('The input array is:',inputvector,)
print('Number of columns in output matrix should be:',no_col_opmat,)
print('Vander matrix of the input array in decreasing order of powers:\n\n',op_matx_dec_order,'\n')
print('Vander matrix of the input array in increasing order of powers:\n\n',op_matx_inc_order,)


The input array is: [1 3 5 7 9]
Number of columns in output matrix should be: 3
Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 9  3  1]
 [25  5  1]
 [49  7  1]
 [81  9  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  7 49]
 [ 1  9 81]] 

The input array is: [ 2  4  6  8 10]
Number of columns in output matrix should be: 5
Vander matrix of the input array in decreasing order of powers:

 [[   16     8     4     2     1]
 [  256    64    16     4     1]
 [ 1296   216    36     6     1]
 [ 4096   512    64     8     1]
 [10000  1000   100    10     1]] 

Vander matrix of the input array in increasing order of powers:

 [[    1     2     4     8    16]
 [    1     4    16    64   256]
 [    1     6    36   216  1296]
 [    1     8    64   512  4096]
 [    1    10   100  1000 10000]]
